name: mfsao
description: My Flutter-specific analysis options
version: 3.0.0
homepage: https://www.github.com/jogboms/mfsao

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter_lints: ^2.0.1
